### ISSUE TITLE
@media print be externalised into a print.less

### ISSUE THREAD

**Issue by dowda** [WestpacCXTeam/GUI-source#164]
Could we have a print.less instead of @media print in individual less files.  This will help us keep everything print related in one place

cheers
Elma Fudd

**Comment by dominikwilkowski** [comment]
Hey Dowie

Great idea. I would suggest a package like [grunt-match-media](https://github.com/mstrutt/grunt-match-media) to extract all media queries including the print ones.
The reason we have them on a module level is that we develop each module in isolation so that you can use them in the blender. Dependencies are kept to a minimum.

Hope this helps. Feel free to open this issue again if you have further questions bout it.
