### ISSUE TITLE
Dropdown button - dismiss dropdown

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#270]
In Firefox the dropdown is not dismissed when clicking outside the dropdown.
In Chrome the dropdown is dismissed when clicked outside the dropdown.

**Comment by dominikwilkowski** [comment]
That's a known issue with Firefox(or better yet the specs) and there is currently no work around. Pseudo elements do not have a DOM representation and don't bubble up events according to the specs. However Chrome and most other browsers ignore this which is why it works there. Firefox is specs compliant here.
I'll close this for now until something surfaces that will enable us to do this.
