### ISSUE TITLE
St.George page header - Fraxel background is missing

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#288]
Not sure why this is missing. Nothing has changed recently in St.George

**Comment by dominikwilkowski** [comment]
So that issue was caused because we changed the BSA and BOM header and because the module is the very same for all brands it unfortunately broke the STG header. I made the "wise" decision to name the two SVGs the same between BSA and STG which of course broke :)

I just fixed that and pushed it up  and merged with master. @diced-dev when you build the docs next this will just be fixed but please double check ;)

**Comment by diced-dev** [comment]
Will do @dominikwilkowski, cheers!
