### ISSUE TITLE
Block level buttons not displaying properly in Docs on iPhone

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#298]
1. On iPhone go to Buttons - Block buttons
2. See attached.
Works fine on desktop.

![img_1883](https://cloud.githubusercontent.com/assets/936597/21215091/0ae619f2-c2f3-11e6-955f-f01ae8a3fa3a.PNG)

**Comment by diced-dev** [comment]
This is happening due to the button group being wider than the iframe and it's pushing the iframe, and everything else inside it, out on iOS Safari.

I don't think this is a bug, as the issue is that the button group is too wide for the iframe and has been designed not to wrap. It's a content issue.
