### ISSUE TITLE
Inconsistent PNG output across installs when converting SVGs

### ISSUE THREAD

**Issue by diced-dev** [WestpacCXTeam/GUI-source#303]
Description
-----------

This may be an OS related bug, but currently 2 different installs of the GUI-modules repo (1 pc and 1 mac) will generate different PNG outputs when a module containing SVGs is built.

Discrepancies in package versions between the two installs were noted and resolved (notably grunticon and phantomjs), however this still did not resolve the issue.

The actual PNG output is correct and all other outputs from grunticon are correct, however because of the changes to files that are actually unchanged the issue is resulting in unnecessary commits to the module repos that contain SVGs.

Steps to Reproduce
------------------

1. Run `grunt` in a specific module containing SVGs or in GUI-modules run `grunt ubergrunt` to build all modules
2. Look at the working copy diff in your git client to see PNG output files changes, even though their source SVGs are unchanged.

**Comment by jonnystening** [comment]
I was noticing differences in the acsii encoding of the = symbol between machines (= vs %3D). Turned out to be that the two machines were running slightly different versions of Grunticon; which was updated, some browsers had trouble with un-encoded ='s in data uri format (https://github.com/filamentgroup/directory-encoder/commit/f62b12e70f36904bde43d7adf4d98fc4c7eff993). 

All package.json files have now been bumped to the latest, including GUI-modules' own package.json (used by the ubergrunt task).

**Please ensure your npm deps are as per package.json. Do a `rm -rf node_modules` and `npm install` to start again just to be sure to be sure 🍀**

**Comment by jonnystening** [comment]
Closing this, but will keep an eye on it 🕵️
