### ISSUE TITLE
Additional icon size (+ icon library refresh)

### ISSUE THREAD

**Issue by justinspencer** [WestpacCXTeam/GUI-source#360]
We're getting a few designers saying the 32px icons are too big. We've agreed to allow designers to use icons at 24px. This is not ideal as most of the icons will fall off the pixel grid however we need to address this issue asap. We need to figure out a way to add another class to icon-base to accomodate this additional size.

**Comment by jonnystening** [comment]
We're going to introduce a fourth icon size (xlg: 48px), and tweak the currently sizing as per the following...

sm: 16px  ---> 18px
md: 32px  ---> 24px
lg:   64px  ---> 36px
xlg:                    48px

The current `lg` size is unnecessarily large (was 64px) so has been removed. Icons have been redrawn to ensure they're optimised to sit on the pixel grid at each of these sizes; ensuring they're crisp as crisp can be.

nb. This will be introduced as a v2.0.0 update as it's a 'breaking' change due to the (involving HTML class updates).

**Comment by jonnystening** [comment]
https://westpaccxteam.github.io/GUI-icons/tests/WBC/
